before_script:
  - "nohup bundle exec ruby spec/support/integration_servers.rb &"
  - "sleep 2"

env:
 - SERVER=Streaming

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - rbx
  - ree

matrix:
  allow_failures:
    - rvm: jruby